<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_Insured</name>
   <tag></tag>
   <elementGuidId>29a68bd5-7811-4f42-9a75-47b05c1786e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@class='ng-binding'][contains(text(),'Insured')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@class='ng-binding'][contains(text(),'Insured')]</value>
   </webElementProperties>
</WebElementEntity>
