<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_nonPremiumVoid_item1</name>
   <tag></tag>
   <elementGuidId>6b834a10-65f1-4d5e-a7c1-999a8f791cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//a[@ng-click='void(item)'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//a[@ng-click='void(item)'])[1]</value>
   </webElementProperties>
</WebElementEntity>
